/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x1C, 0x87, 0xA9, 0xA7, 0xA2, 0x9E, 0x86, 0x95}

#define VIAL_UNLOCK_COMBO_ROWS {0, 3}
#define VIAL_UNLOCK_COMBO_COLS {0, 13}

#define LSPO_KEYS KC_LSFT, KC_LSFT, KC_9
#define RSPC_KEYS KC_RSFT, KC_RSFT, KC_0

#define LCPO_KEYS KC_LCTL, KC_LSFT, KC_LBRC
#define RCPC_KEYS KC_RCTL, KC_RSFT, KC_RBRC

#define LAPO_KEYS KC_LALT, KC_TRNS, KC_LBRC
#define RAPC_KEYS KC_RALT, KC_TRNS, KC_RBRC

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define RGB_MATRIX_STARTUP_HUE 240
#define RGB_MATRIX_STARTUP_SAT 63
#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
